### ISSUE TITLE
A simple SEIR model

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityAnalysis.jl#195]
A simple SEIR model was shared [on discourse](https://discourse.julialang.org/t/an-interactive-notebook-for-a-simple-seir-model/39847); in the notebook linked there's also a beautiful interactive plot. I was planning to add one of such models to the documentation of this package, as it's a case where, naturally, parameter values are not known precisely.

If we model the parameter uncertainties as variables with zero dynamics and an uncertain initial set, the computed flowpipe contains (an overapproximation of) all possible trajectories for the SEIR model for any combination of parameter choices on the given uncertain initial set. In the next paragraph i show some possible algorithm parameter choices.  
I didn't model variation in `E₀` though that's also possible.

cc @dpsanders 

---

```julia
using ReachabilityAnalysis

@taylorize function seir2!(du,u,p,t)
  S, E, I, R, α, β, γ = u

  βIS = β * (I * S)
  αE = α*E
  γI = γ*I

  du[1] = -βIS      # dS
  du[2] = βIS - αE  # dE
  du[3] = -γI + αE  # dI
  du[4] = γI        # dR

  # uncertain parameters  param_error = 0.05
  local zerou = zero(u[1])
  du[5] = zerou # α = 0.2 ± param_error
  du[6] = zerou # β = 0.5 ± param_error
  du[7] = zerou # γ = 0.5 ± param_error
end

E₀ = 1e-4
u₀ = [1-E₀, E₀, 0, 0]
param_error = 0.001
α = 0.2 ± param_error
β = 0.5 ± param_error
γ = 0.5 ± param_error
p = [α, β, γ]
X0 = IntervalBox(vcat(u₀, p));
prob = @ivp(x' = seir2!(x), dim=7, x(0) ∈ X0);

@time sol = solve(prob, tspan=(0.0, 200.0), alg=TMJets(abs_tol=1e-10, orderT=7, orderQ=1, adaptive=true));
  1.779561 seconds (29.73 M allocations: 2.026 GiB, 25.38% gc time)


solz = overapproximate(sol, Zonotope);

LazySets.set_ztol(Float64, 1e-12)
fig = plot(legend=:bottomright)

#plot!(fig, solz, vars=(0, 1), color=:blue, lw=0.0, lab="S")
plot!(fig, solz, vars=(0, 2), color=:blue, lw=0.0, lab="E")
plot!(solz, vars=(0, 3), color=:red, lw=0.0, lab="I")
#plot!(solz, vars=(0, 4), color=:blue, lw=0.0, lab="R")

```

![Screenshot from 2020-05-21 14-13-01](https://user-images.githubusercontent.com/12424594/82586018-50596d80-9b6d-11ea-9b82-af73b5c95504.png)

---

EDIT: new notebook, with trajectories https://github.com/mforets/escritoire/blob/master/2020/Week23/SEIR_v2.ipynb

**Comment by lbenet** [comment]
Very nice!

**Comment by dpsanders** [comment]
Great! But those values of E and I seem very small?

**Comment by mforets** [comment]
The original notebook also uses the small value `E₀ = 1e-4`, but in the plot, he multiplies the solution by 100. We can do that here with a linear transformation on the flowpipe (which is exact):

```julia
solz = [ReachSet(linear_map(Matrix(100.0I, 7, 7), set(R)), tspan(R)) for R in solz];
```

![Screenshot from 2020-05-21 14-31-36](https://user-images.githubusercontent.com/12424594/82587575-d1b1ff80-9b6f-11ea-94d5-b172b3488f11.png)
