### ISSUE TITLE
Test (in mac) currently failing due to incompatible version

### ISSUE THREAD

**Issue by lbenet** [JuliaReach/ReachabilityAnalysis.jl#231]
I am reporting that tests (in mac) are currently failing due to some incompatibility; see [here](https://travis-ci.com/github/JuliaReach/ReachabilityAnalysis.jl/jobs/350570177#L593), though there seems to be more  going on (since linux tests are also failling).

The problem is related to GLPK.jl, which has been already reported https://github.com/JuliaOpt/GLPK.jl/issues/140, and a solution is on its way (https://github.com/JuliaRegistries/General/pull/16517). As a possible work around, see [this comment](https://github.com/JuliaOpt/GLPK.jl/issues/140#issuecomment-645541238).

**Comment by mforets** [comment]
Thanks a lot for digging into this issue! If tomorrow this hasn't been fixed i can try adding `GMP_jll@6.1.2` to the travis script.

**Comment by mforets** [comment]
Seems fixed now.
