### ISSUE TITLE
Add method to @map

### ISSUE THREAD

**Issue by dfcaporale** [JuliaReach/ReachabilityAnalysis.jl#278]
```
guard = HalfSpace(sparsevec([1], [-1.], 5), 100.)
t1 = @map(x -> x, dim: 5, x ∈ guard)
```

MethodError: no method matching @map(::LineNumberNode, ::Module, ::Expr, ::Expr, ::Expr)
Closest candidates are:
  @map(::LineNumberNode, ::Module, ::Any, ::Any) at C:\Users\danie\.julia\dev\MathematicalSystems\src\macros.jl:59
  @map(::LineNumberNode, ::Module, ::Any) at C:\Users\danie\.julia\dev\MathematicalSystems\src\macros.jl:76

**Comment by mforets** [comment]
thanks for the report. this issue is particular to MathematicalSystems.jl.
however, i can't reprduce it, i think we solved this in the latest patch release of MathematicalSystems (https://github.com/JuliaReach/MathematicalSystems.jl/releases/tag/v0.11.4). can you try

```julia
] up MathematicalSystems
```
?

**Comment by dfcaporale** [comment]
Great! It worked once I removed the old package and re-installed MathematicalSystems. Thanks!
