### ISSUE TITLE
Wrong title in Lorenz example in documentation

### ISSUE THREAD

**Issue by SebastianGuadalupe** [JuliaReach/ReachabilityAnalysis.jl#299]
https://juliareach.github.io/ReachabilityAnalysis.jl/dev/models/lorenz/

**Comment by mforets** [comment]
thanks. i'll be bumping most model docs shortly. i can fix this one too.

**Comment by schillic** [comment]
Let me add that the Platoon model is twice in the list :slightly_smiling_face:
