### ISSUE TITLE
Approximation at time points

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityAnalysis.jl#421]
- for taylor model reach-sets: extend https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/master/src/Flowpipes/reachsets.jl#L806 to accept a point.

- in fact we can make `fp(t)` evaluate at the given time point

related to https://github.com/JuliaReach/NeuralNetworkAnalysis.jl/issues/90

**Comment by schillic** [comment]
I believe this is now supported.
