### ISSUE TITLE
Repo size is too big

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityAnalysis.jl#428]
- how to (permanently) delete old PR previews from the gh-pages branch?
    - see https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#gh-pages-Branch
    
- how to save additional space?

**Comment by schillic** [comment]
That works but it only removes the last PR. And if the PR is closed before the preview is pushed, that run errors and does not remove the folder. To remove all previews from the history, one can do this locally:

```bash
git rm -rf "previews/PR*"
git commit -m "delete previews"
git branch gh-pages-new $(echo "delete history" | git commit-tree HEAD^{tree})
git push --force origin gh-pages-new:gh-pages
```

**Comment by mforets** [comment]
the size of this repo is now at 1010MB as listed in: https://github.com/settings/repositories  (probably requires admin access). that's huge!

@schillic thanks for your tip to cleanup previous previews. i'll try it shortly.

the Literate.jl docs contain another idea for reducing the size of generated notebooks: https://fredrikekre.github.io/Literate.jl/v2/tips/

we can try storing all images as PNG. however, i didn't quite understand the Note in blue ("It is best to always let the object be showable as text/plain" << then we should always use `img = DisplayAs.Text(DisplayAs.PNG(img))` ?

**Comment by mforets** [comment]
ok, i see. yeah no problem with deleting older docs pages. that is still very much WIP
