### ISSUE TITLE
Inconsistent flowpipes with TMJets

### ISSUE THREAD

**Issue by schillic** [JuliaReach/ReachabilityAnalysis.jl#468]
Different time horizons `T` result in contradictory flowpipes for `TMJets`. The behavior changes for different values of `orderT`.

![flowpipes](https://user-images.githubusercontent.com/9656686/117249366-b9e79000-ae41-11eb-90eb-603cf8643f0d.png)

```julia
using ReachabilityAnalysis, Plots
using ReachabilityAnalysis: post

function dynamics!(dx, x, p, t)
    dx[1] = x[2]
    dx[2] = 2 * sin(x[1]) + 8 * x[3]
    dx[3] = zero(x[1])
    return dx
end;

X0 = Singleton([1.2, 0.2, -0.78]);
ivp = @ivp(x' = dynamics!(x), dim: 3, x(0) ∈ X0);
cpost = TMJets(abs_tol=1e-8, orderT=10, orderQ=3);
Ts = [0.03, 0.04];

sols = Flowpipe[];
for T in Ts
    sol = post(cpost, ivp, 0 .. T)
    push!(sols, sol)
end;

vars = (0, 1);
fig = plot(legend=:bottomright);
for i in 1:length(Ts)
    T = Ts[i]
    sol = sols[i]
    plot!(fig, sol, vars=vars, lab="T=$T")
end;
fig
```

**Comment by mforets** [comment]
this is now fixed on master, the result is:

![Screenshot from 2021-05-15 10-19-08](https://user-images.githubusercontent.com/12424594/118362819-a20dbb80-b567-11eb-990e-06b2aaacf418.png)
