### ISSUE TITLE
Operations with zonotopes in the documentation 

### ISSUE THREAD

**Issue by ga72kud** [JuliaReach/ReachabilityAnalysis.jl#597]
Thank you a lot for the awesome package. I have some questions about the documentation. 

Currently I am wondering about the section Operations with Zonotopesj from:

https://juliareach.github.io/ReachabilityAnalysis.jl/dev/tutorials/set_representations/zonotopes/

1. Is the computational cost (Big O operator) really 2mn(k+1) or mn(k+1). I am wondering about the 2. 
2. Is this the description for a inner product. ⟨v1​,⋯,vk​⟩. Is this right for the zonotope. Is it not a generator set? For a set I would use {v1​,⋯,vk​} other brackets. 
3. I do not understand CH(Z1​,eAδZ1​)⊆21​(c+eAδc,⟨v1​+eAδv1​,⋯,vk​+eAδvk​,v1​−eAδv1​,vk​−eAδvk​,c−eAδc⟩) and how you come to the cost. What kind of A matrix (no definition) n x n matrix?

**Comment by mforets** [comment]
> Is the computational cost (Big O operator) really 2mn(k+1) or mn(k+1). I am wondering about the 2.

The confusion arises from the fact that the "Cost" column was chosen to measure the number of binary operations, so for example a size 3x3 matrix times a length 3 vector (using the naive multiplication computation) involve three products and two sums per row, so it's an O(n^2 + (n-1)*n)) = O(2n^2). For reference see [this article](http://mediatum.ub.tum.de/doc/1379695/23911.pdf).

> Is this the description for a inner product. ⟨v1​,⋯,vk​⟩. Is this right for the zonotope. Is it not a generator set? For a set I would use {v1​,⋯,vk​} other brackets.

Yeah such notation `<...>` is used in some articles, but I agree it may be confused with the inner product notation. What is meant here is horizontal concatenation of the generators, i.e.

```julia
julia> v1 = [1.0, 2.0];

julia> v2 = [3.0, 4.0];

julia> [v1 v2]
2×2 Matrix{Float64}:
 1.0  3.0
 2.0  4.0
```
I think using the curly braces as you suggest, or using square braces such as `[v1 v2, ..., vn]`, are both fine alternatives.
