### ISSUE TITLE
Example plot fails (tickfont_pointsize) (Plots regression)

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityAnalysis.jl#606]
See [this comment](https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/605#issuecomment-1058547852)

**Comment by schillic** [comment]
This is a `Plots` regression. I reported it.

**Comment by schillic** [comment]
This was fixed and will be in the next `Plots` release (1.27.3).
