### ISSUE TITLE
ReachabilityAnalysis

### ISSUE THREAD

**Issue by ga72kud** [JuliaReach/ReachabilityAnalysis.jl#610]
I use the ReachabilityAnalysis package in a certain environment. After some time it cannot compile without knowing the cause. I only changed the environment. Before I used another environment with LazySets, Symbolics. I don't know what was the cause of this issue

LoadError: LoadError: LoadError: Failed to precompile ReachabilityAnalysis [1e97bd63-91d1-579d-8e8d-501d2b57c93f] to /home/michael/.julia/compiled/v1.6/ReachabilityAnalysis/jl_xo2dZX.
in expression starting at /home/michael/Julia_Projects/25_thesis/src/visualization/visualizer.jl:1
in expression starting at /home/michael/Julia_Projects/25_thesis/src/agents/vehicle.jl:1
in expression starting at /home/michael/Julia_Projects/25_thesis/main.jl:1
error(s::String) at error.jl:33
compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY, ignore_loaded_modules::Bool) at loading.jl:1385
compilecache(pkg::Base.PkgId, path::String) at loading.jl:1329
_require(pkg::Base.PkgId) at loading.jl:1043
require(uuidkey::Base.PkgId) at loading.jl:936
require(into::Module, mod::Symbol) at loading.jl:923
eval at boot.jl:360 [inlined]
include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String) at loading.jl:1116
_include(mapexpr::Function, mod::Module, _path::String) at loading.jl:1170
include(mod::Module, _path::String) at Base.jl:384
include(x::String) at vehicle.jl:1
top-level scope at vehicle.jl:7
eval at boot.jl:360 [inlined]
include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String) at loading.jl:1116
_include(mapexpr::Function, mod::Module, _path::String) at loading.jl:1170
include(fname::String) at client.jl:444
top-level scope at main.jl:1
eval at boot.jl:360 [inlined]
include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String) at loading.jl:1116

status
  [a81c6b42] Compose v0.9.3
  [b4f34e82] Distances v0.10.7
  [31c24e10] Distributions v0.25.49
  [c87230d0] FFMPEG v0.4.1
  [c91e804a] Gadfly v1.3.4
  [4b11ee91] Gaston v1.0.4
  [c601a237] Interact v0.10.4
  [b6b21f68] Ipopt v0.7.0
  [4076af6c] JuMP v0.21.5
  [283c5d60] MeshCat v0.13.2
  [510215fc] Observables v0.4.0
  [d96e819e] Parameters v0.12.3
  [1e97bd63] ReachabilityAnalysis v0.16.5
  [38ceca67] RobotDynamics v0.3.4
  [74be38bb] RobotZoo v0.2.3
  [6038ab10] Rotations v1.2.0
  [90137ffa] StaticArrays v1.3.5
  [7770976a] TrajOptPlots v0.2.0
  [c79d492b] TrajectoryOptimization v0.5.0

Julia 1.6

**Comment by ga72kud** [comment]
Using an older version of the project solved the issue

**Comment by lbenet** [comment]
Just for (future) reference: which was the package causing the problems?

**Comment by ga72kud** [comment]
Hi @lbenet, I don't know. How can it find it out for the future? Now it is solved by a workaround.
