### ISSUE TITLE
Type piracy for `LinearAlgebra.I`

### ISSUE THREAD

**Issue by baggepinnen** [JuliaReach/ReachabilityAnalysis.jl#649]
Importing this package completely breaks `LinearAlgebra.I` and all code that makes use of it:
```julia
julia> using LinearAlgebra

julia> I(2)
2×2 Diagonal{Bool, Vector{Bool}}:
 1  ⋅
 ⋅  1

julia> import ReachabilityAnalysis as RA

julia> I(2)
MathematicalSystems.IdentityMultiple{Float64} of value 1.0 and order 2
```
Notice that the code above does not import any names from ReachabilityAnalysis, still the `I` was overridden. Importing this packages thus breaks all code in every package that uses `LinearAlgebra.I`.

Tested with ReachabilityAnalysis v0.18.7

**Comment by baggepinnen** [comment]
I just noticed that the offending method lives in MathematicalSystems.jl

**Comment by mforets** [comment]
Thanks for opening the issue. I think we can close this, since it was fixed upsteam.
