### ISSUE TITLE
References for the quadrotor example

### ISSUE THREAD

**Issue by adeyemiadeoye** [JuliaReach/ReachabilityAnalysis.jl#669]
[Currently](https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/master/examples/Quadrotor/Quadrotor.jl), it is given as `xxx`: `We study the dynamics of a quadrotor as derived in [xxx]`

**Comment by mforets** [comment]
The relevant references are:

- Eq. (16-19) in Beard, R. (2008). Quadrotor Dynamics and Control Rev 0.1 . Technical Report Brigham Young University
- Geretti, L., Sandretto, J. A. D., Althoff, M., Benet, L., Chapoutot, A., Collins, P., Duggirala, P. S., Forets, M.,800
Kim, E., Linares, U., Sanders, D. P., Schilling, C., & Wetzlinger, M. (2021). ARCH-COMP21 category report:801
Continuous and hybrid systems with nonlinear dynamics. In ARCH (pp. 32–54). EasyChair volume 80 of EPiC802
Series in Computing. doi:10.29007/2jw8
