### ISSUE TITLE
Broken Model Example Links in main README.md

### ISSUE THREAD

**Issue by EthanJamesLew** [JuliaReach/ReachabilityAnalysis.jl#713]
**Describe the bug**

Under the Features section of the main README.md, some of the example links (e.g., Platoon and Spacecraft) are broken.

**To Reproduce**

1. Click on the link of the line (line 104 on commit 9ae5af)
```markdown
<p> <a href="https://juliareach.github.io/ReachabilityAnalysis.jl/dev/models/Spacecraft/">Spacecraft</a> </p>
```

**Expected behavior**

A link to a doc page like the `generated_examples`: https://juliareach.github.io/ReachabilityAnalysis.jl/dev/generated_examples/Spacecraft/

**Comment by mforets** [comment]
Thanks for the pointer! Those models should work, so we need to update the hyperlinks. 

Identification can be automated with this tool  https://www.deadlinkchecker.com/website-dead-link-checker.asp which shows 19 potential issues with links on the main README.

**Comment by mforets** [comment]
Fixed in https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/714
