### ISSUE TITLE
Move `relative_error` to ReachabilityBase

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityAnalysis.jl#727]
https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/master/src/Flowpipes/setops.jl#L464

**Comment by schillic** [comment]
This does not work because the code uses `IntervalArithmetic.Interval`, which is not available in ReachabilityBase. And since the name `relative_error` suggests an application with approximation, I think the function is best kept here.
