### ISSUE TITLE
Failure to run some examples due to both Plots and ReachabilityAnalysis exporting "center"

### ISSUE THREAD

**Issue by hurak** [JuliaReach/ReachabilityAnalysis.jl#751]
I am not sure if the following qualifies as an issue, but it certainly prevents some examples from the webpage from running successfully just by running the copy-pasting their code: for example, the one from https://juliareach.github.io/ReachabilityAnalysis.jl/dev/tutorials/linear_methods/discrete_time/.

Namely, both Plots and ReachabilityAnalysis export "center". As a result, the following code

```julia
using ReachabilityAnalysis, Plots
X0 = BallInf(ones(2), 0.2)
plot(X0, c=:white)
c = center(X0) 
```

returns the error 

```WARNING: both Plots and ReachabilityAnalysis export "center"; uses of it in module Main must be qualified
ERROR: UndefVarError: `center` not defined
```
As a result the example code on the above linked webpage cannot be run without adding the full qualification:

```julia
c = ReachabilityAnalysis.center(X0)
```

but this should better be included in the example code directly. 

Unless there is a neater solution.

**Comment by mforets** [comment]
i think this is a known issue; `Plots`  exports `center` (why?!) and so does `LazySets`.

**Comment by mforets** [comment]
looking at the code i see that we are hiding the relevant line https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/master/docs/src/tutorials/linear_methods/discrete_time.md

```julia
using ReachabilityAnalysis # hide
using ReachabilityAnalysis: center  # hide
```

but showing them seems better, to avoid confusion.

**Comment by mforets** [comment]
being done in https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/752
